### ISSUE TITLE
avers-server-0.0.4 fails to build with servant-0.7?

### ISSUE THREAD

**Issue by juhp** [wereHamster/avers-server#1]
From the Stackage Nightly build:

```
Preprocessing library avers-server-0.0.4...
[1 of 3] Compiling Avers.Server.Instances ( src/Avers/Server/Instances.hs, dist/build/Avers/Server/Instances.o )

src/Avers/Server/Instances.hs:37:37:
    Not in scope: data constructor ‘WithRequest’
    Perhaps you meant one of these:
      variable ‘withRequest’ (imported from Servant.Server.Internal),
      variable ‘ifRequest’ (imported from Network.Wai)

src/Avers/Server/Instances.hs:56:37:
    Not in scope: data constructor ‘WithRequest’
    Perhaps you meant one of these:
      variable ‘withRequest’ (imported from Servant.Server.Internal),
      variable ‘ifRequest’ (imported from Network.Wai)
```

**Comment by wereHamster** [comment]
*sigh* I can't keep up with all the breaking changes in servant :( I just upgraded avers-* to be compatible with servant 0.6 a week ago.

**Comment by juhp** [comment]
Yep I thanks I know and understand.  There is no rush, except we might release LTS 6 before too long.

Perhaps you want to add an upper bound for servant?

**Comment by wereHamster** [comment]
I released 0.0.5 which should build with servant 0.7.1

**Comment by juhp** [comment]
Thank you very much
